# Site settings
title: Raja Trucking, LLC
description:
  An uprising freight transportation company that provides services for freight brokers and various companies to locations throughout the 48 states.
timezone: America/Dallas

# URLs
baseurl:
url: https://rajatrucking.net
permalink: pretty

# Structure configuration
source: docs/
destination: _site/

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - README.md
  - gulpfile.js
  - package.json
  - package-lock.json
  - ignores
  - node_modules
  - gulp


defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/trucks/blue_2.JPG
      height: 1072
      width: 2048
