# Site settings
title: Raja Trucking, LLC.
author: Raja Trucking, LLC.
email: rajatrucking@sbcglobal.net
description:
  Raja Trucking, LLC. is an uprising freight transportation company that provides services for freight brokers and various companies to locations throughout the 48 states. We have been in business in the Fort Worth, TX area since May 2006. Raja Trucking, LLC. is operating with about 30 drivers providing power only, intermodal, and over the road (OTR) services.
timezone: America/Dallas

# URLs
baseurl: "/rajatrucking"
url: "https://job-talk.github.io"
permalink: pretty

# Structure configuration
source: ./
destination: ./_site

# Build settings
markdown: kramdown

gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - LICENSE
  - README.md

sass:
  sass_dir: _sass
  style: compressed
  
seo:
  title: 'Raja Trucking, LLC.'
  description: 'Raja Trucking, LLC. is an uprising freight transportation company that provides services for freight brokers and various companies to locations throughout the 48 states. We have been in business in the Fort Worth, TX area since May 2006. Raja Trucking, LLC. is operating with about 30 drivers providing power only, intermodal, and over the road (OTR) services.'
  url:
  google_site_verification:
